server:
  port: 8026

spring:
  application:
    name: qq-service

  # ???????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/smscode
    username: root
    password: 123456789
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000

  # Jackson ??????????? Fastjson2?? SpringBoot ????????? Jackson?
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

  # ??????
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
    encoding:
      charset: UTF-8
      force: true

# MyBatis-Plus ??
mybatis-plus:
  # XML ????????
  mapper-locations: classpath*:/mapper/**/*.xml
  # ?????????????
  type-aliases-package: com.wzz.entity
  configuration:
    # ?????????????underline_to_camel?
    map-underscore-to-camel-case: true
    # ?? SQL ????????????????????? log4j2 ???
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # ???? (AUTO:?????, ASSIGN_ID:????)
      id-type: auto
      # ???????
#      logic-delete-field: deleted
      # ??????
#      logic-not-delete-value: 0
      # ??????
#      logic-delete-value: 1

# Sa-Token ??
sa-token:
  # token ?? (???? cookie ??)
  token-name: qq
  # token ??????? ??30??-1??????
  timeout: 2592000
  # token ????? (??????????? token ??) ???
  active-timeout: -1
  # ???????????? (? true ???????, ? false ?????????)
  is-concurrent: true
  # ????????????????? token (? true ???, ? false ??????? token)
  is-share: true
  # token ??
  token-style: uuid
  # ??? header ?? token
  is-read-header: true
  # ???? Login ??
  is-log: false
  # JWT ?? (?? sa-token-jwt ????????????????)
  jwt-secret-key: faksjdhflaksjdfhalskdjfhalskdjfhalskdjfh

# ???? (???? log4j2 ????)
logging:
  config: classpath:log4j2-spring.xml
  level:
    root: info
    com.wzz.mapper: debug # ???? Mapper ??????

#????????????
DatabaseInitService:
  path: com.wzz.qq.entity
